clickhouse:
  db: default
  table: record
  host: localhost
  port: 9000
  credentials:
    user: default
    password:
  columns:
    time: $1(time)
    time_utc: $1(time_utc)
    name: aggregation.key1
    action: $2
    duration: aggregation.kk(int32)
    id: dynamic.id
  Preprocessing:
    aggregation:
      key1: $2[1:3]+"$key "+$3[:2]
      kk: $4[3:]
      $5: $4
    static:
      a: 1
    dynamic:
      id: gen_uuid()



setting:
  file_path: ./test/demo.log
  max_line_every_read: 200
  interval: 10  # in milliseconds(ms)
  mode: follower

    