clickhouse:
  db: metrics
  table: engine_log2
  host: localhost
  port: 9000
  credentials:
    user: default
    password:
  columns:
    time: $1(time)
    action: $2
    uid: $3(int32)
    market: $4 


setting:
  file_path: /Users/ollie/Desktop/gate/fu/all.log
  max_line_every_read: 200
  interval: 10  # in milliseconds(ms)
  mode: follower

    