clickhouse:
  db: default
  table: engine_log2
  host: localhost
  port: 9000
  credentials:
    user: default
    password:
  columns:
    time: $1(time)
    action: $3[1:](string)
    uid: $4(int32)
    market: $5


setting:
  file_path: test.log
  max_line_every_read: 200
  interval: 10  # in milliseconds(ms)

    