clickhouse:
  db: metrics
  table: access_log
  host: localhost
  port: 9000
  credentials:
    user: default
    password:
  columns:
    time: $1(time)
    action: $2
    uid: $3(int32)
    market: $4 

file:
  path: /Users/ollie/Desktop/gate/fu/all.log

    